### ISSUE TITLE
Specify the backend

### ISSUE THREAD

**Issue by YassineE** [heetch/confita#11]
In order to avoid some useless processing we can specify for a field in which backend we can find its value. 

e.g. 
```go
type Config struct {
  Foo        string        `config:"foo",bcknd:"etcd"`
  Bar        string        `config:"bar",bcknd:"consul"`
}
```

**Comment by arkan** [comment]
Good idea! 
🌷 Just don't know if `bcknd` is a typo or on purpose, but `backend` is probably better

**Comment by YassineE** [comment]
@arkan actually it was on purpose but you're right `backend` is better.
I thought that `backend` is a bit too long.
