### ISSUE TITLE
default value as fallback

### ISSUE THREAD

**Issue by mogudy** [heetch/confita#29]
Hi , I was looking for a config loading tool and this is exactly the one.
After several apps, we found that config file or other source is not always reliable.
In the case failed to retrievce config files, we have to manually set a default value for crucial fields.
Is it possible to have a default value written in tag? 

Very apppreciate for it.

**Comment by asdine** [comment]
Hi, thank you for your kind words!
Actually, default values can simply be filled when instantiating your type before telling Confita to load the configuration. There is an example [here](https://github.com/heetch/confita#default-values)
