### ISSUE TITLE
parse yaml file failled, I have that key but confita said not found

### ISSUE THREAD

**Issue by CrazyPandas** [heetch/confita#53]
hi, guys.
I met some trouble with use confita. Anybody can help me?Please.
I have a nest struct:
```go
type Database struct {
	Which 	string  `config:"which"`
	DbDir 	string	`config:"db_dir"`
}

type Config struct {
	Database Database 	`config:"database,required"`
	AppName string 		`config:"app_name,required"`
}
```
and then,when i use [goconvey](https://github.com/smartystreets/goconvey/) to test, it failed.
here is my code:
```go
func createTempFile(name, content string) (string, func()) {
	dir, err := ioutil.TempDir("", "testDir")
	So(err, ShouldBeNil)

	path := filepath.Join(dir, name)
	f, err := os.Create(path)
	So(err, ShouldBeNil)

	_, err = fmt.Fprint(f, content)
	So(err, ShouldBeNil)
	So(f.Close(), ShouldBeNil)

	return path, func() {
		So(os.RemoveAll(dir), ShouldBeNil)
	}
}

func TestLoadWithTempFile(t *testing.T) {
	Convey("test Load with temp file", t, func() {
		var cfg Config
		path, cleanUp := createTempFile("app.yaml", `
app_name: blog
database:
  which: sqlite3
  db_dir: /tmp/test.db
`)
		defer cleanUp()

		loader := confita.NewLoader(file.NewBackend(path))
		err := loader.Load(context.Background(), &cfg)

		So(err, ShouldBeNil)
		So(cfg.Database, ShouldNotBeNil)
		So(cfg.AppName, ShouldEqual, "blog")
		So(cfg.Database.Which, ShouldEqual, "sqlite3")
		So(cfg.Database.DbDir, ShouldEqual, "/tmp/test.db")
	})
}
```

and the test result:
```go
....x.
Failures:

  * /home/lks/go/src/github.com/crazypandas/goBlog/config/config_test.go 
  Line 46:
  Expected: nil
  Actual:   'required key 'app_name' for field 'AppName' not found'


6 total assertions
```
Is there anything wrong?

**Comment by thekondor** [comment]
The problem here is that `confita` doesn't propagate keys' names specified within `config` tags to underlying decoders. So `yaml` decoder should be aware that `AppName` field is mapped to `app_name` key value.

`AppName` field with a `yaml` tag added will solve the issue:

```go
    type Config struct {
	Database Database 	`config:"database,required"`
	AppName string 	        `config:"app_name,required" yaml:"app_name"`
    }
```

**Comment by CrazyPandas** [comment]
> The problem here is that `confita` doesn't propagate keys' names specified within `config` tags to underlying decoders. So `yaml` decoder should be aware that `AppName` field is mapped to `app_name` key value.
> 
> `AppName` field with a `yaml` tag added will solve the issue:
> 
> ```go
>     type Config struct {
> 	Database Database 	`config:"database,required"`
> 	AppName string 	        `config:"app_name,required" yaml:"app_name"`
>     }
> ```

 @thekondor Thanks for your reply.It works now.
