### ISSUE TITLE
Support "description" tag

### ISSUE THREAD

**Issue by ogerardin** [heetch/confita#56]
Help usage generation would be improved if struct members supported a "description" tag (or a sub-tag of "config"), e.g.

```
type Configuration struct {
	Port          int    `config:"port" description:"listening port number"`
}

```
or

```
type Configuration struct {
	Port          int    `config:"port,description=listening port number"`
}

```

**Comment by steamrolla** [comment]
The above pull request should be closed as the flags backend has changed since it's submission.

A new pull request has been submitted.
