### ISSUE TITLE
Support short/long flags

### ISSUE THREAD

**Issue by ogerardin** [heetch/confita#57]
Most command-line tools support a short and a long form for flags, e.g. "-p" or "--port".
Currently confita only supports a single flag per member. 

Suggestion: add a "short" sub-tag and handle it as a synonym of the default name. Also update help usage generation to reflect this.
```
type Configuration struct {
	Port          int    `config:"port,short=p"`
}

```

**Comment by steamrolla** [comment]
This is ALMOST done... in [flags_test.go](https://github.com/heetch/confita/blob/master/backend/flags/flags_test.go#L18) we are missing a couple types from the struct. Should have this done today, and, this should complete the enhancement.

**Comment by steamrolla** [comment]
should be good.
