### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by steamrolla** [heetch/confita#66]
last commit/pr was brought in coming up on 4 months ago... is this still maintained?

**Comment by YassineE** [comment]
hi @steamrolla, this is indeed still maintained. We just have less time than usual for working on Confita but this will be resolved as soon as possible. 

You are more than welcome to contribute by opening new issues and/or proposing PRs for existing ones.

Thank you for your understanding.

**Comment by steamrolla** [comment]
Awesome - good to hear. I want to start using this at work and wanted to make sure y’all are still there. 🤓

Thank you!
