### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by YassineE** [heetch/confita#7]
IMO we should specify in the doc that when a key is found in a backend, we won't continue to look for it in the remaining backends.

So there is an importance on how the backends are sorted inside the slice.

What do you think ?

**Comment by asdine** [comment]
> Confita scans a struct for config tags and calls all the backends one after another until the key is found

Do you think this sentence is not enough ?

**Comment by YassineE** [comment]
I think we can add more precision like the following:

> FYI the value won't be overrided if the key is present in several backends, the first value found will be returned.
