### ISSUE TITLE
Environment variable specification

### ISSUE THREAD

**Issue by YassineE** [heetch/confita#8]
The [XCU specification](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html) says that the environment variable names consist solely of upper-case letters, digits and the "_" (underscore).

Maybe, we should respect this spec and not handle the case if names contains "-" (dash).

**Comment by asdine** [comment]
We are already handling this in the environment backend actually:
https://github.com/heetch/confita/blob/master/backend/env/env.go#L21

**Comment by YassineE** [comment]
Allright, I close the issue then.
